### ISSUE TITLE
iqua vs ecowater

### ISSUE THREAD

**Issue by krismarc** [ejsuncy/py_ecowater#10]
hey, do you know what's the relation between those 2?

There's another project https://github.com/barleybobs/ecowater-softener which seems to relay on [aylanetworks](https://www.aylanetworks.com/)

Does it mean Eco Water provides different apis? I couldn't find any details about https://apioem.ecowater.com/v1

**Comment by ejsuncy** [comment]
I don't know much apart from the fact that the iQua iOS app sends all its requests to the ecowater api. I created this library for use with the ecowater Prometheus exporter I also maintain, but it turns out that the ecowater api is severely rate limited and they disable your water softener from sending data when you use Prometheus at any usable polling frequency. In fact, I turned off my Prometheus polling entirely and just used the iOS app, but if you have the app open, it still gets rate limited and the iOS app throws errors. IMO it's a garbage service. /rant

**Comment by krismarc** [comment]
Ok, your lib uses https://apioem.ecowater.com/v1. Question is if that other project can be anyhow used to access eco water api with your softener data. Could be that it's available via other api using the same database and that restricted rates are not there.

I gave it a try and I get `ayla_iot_unofficial.exc.AylaAuthError: Invalid Username, Origin oem or password.`
